apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeonec-cs.fullname" . }}
  labels:
    {{- include "kubeonec-cs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubeonec-cs.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kubeonec-cs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubeonec-cs.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          ports:
            - name: elasticsearch
              containerPort: 9300
              protocol: TCP
        - name: hazelcast
          image: "{{ .Values.hazelcast.image.repository }}:{{ .Values.hazelcast.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hazelcast.image.pullPolicy }}
          ports:
            - name: hazelcast
              containerPort: 57001
              protocol: TCP
            - name: web
              containerPort: 8088
              protocol: TCP
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.cs.image.repository }}:{{ .Values.cs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cs.image.pullPolicy }}
          ports:
            - name: websocket
              containerPort: 9094
              protocol: TCP
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: cs-config
            mountPath: /var/cs/cs_instance/config/jdbc.yml
            subPath: jdbc.yml
          - name: cs-config
            mountPath: /var/cs/cs_instance/config/elasticsearch.yml
            subPath: elasticsearch.yml
          - name: cs-config
            mountPath: /var/cs/cs_instance/config/hazelcast.yml
            subPath: hazelcast.yml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: cs-config
        secret:
          secretName: cs-config
